#84 (Add `minos.common.AggregateDiff` class)
Clariteia/minos_microservice_common pull request #323
Opened 2021-06-10 09:47 UTC by garciparedes

Resolves #84

2021-06-10 10:03 UTC, andrea-mucci approved these changes

2021-06-10 11:32 UTC, albamig requested changes
Nice functionality @garciparedes! I would change the interface to the `diffs` though.

I think a better object oriented way to compare two objects is by creating a `diff()` method within the `Aggregate` class that gets an `Aggregate` object you want to compare it to. I'll put an example:

```python
class Aggregate:
    def diff(agg: Aggregate |  Avro):
        ...
```

This way you can calculate a diff by using:

```python
agg1 = Aggregate()
agg2 = Aggregate()
agg1.diff(agg2)
```
rather than the static way:

```python
agg1 = Aggregate()
agg2 = Aggregate()
AggregateDiff.from_aggregate(agg1, agg2)
```
Probably, the `AggregateDiff` class might remain, but it should be encapsulated within the ''diff()` method in order to ease the interaction among objects.

What do you think? :rocket:

2021-06-10 11:40 UTC, garciparedes commented
> Nice functionality @garciparedes! I would change the interface to the `diffs` though.
> 
> I think a better object oriented way to compare two objects is by creating a `diff()` method within the `Aggregate` class that gets an `Aggregate` object you want to compare it to. I'll put an example:
> 
> ```python
> class Aggregate:
>     def diff(agg: Aggregate |  Avro):
>         ...
> ```
> 
> This way you can calculate a diff by using:
> 
> ```python
> agg1 = Aggregate()
> agg2 = Aggregate()
> agg1.diff(agg2)
> ```
> 
> rather than the static way:
> 
> ```python
> agg1 = Aggregate()
> agg2 = Aggregate()
> AggregateDiff.from_aggregate(agg1, agg2)
> ```
> 
> Probably, the `AggregateDiff` class might remain, but it should be encapsulated within the ''diff()` method in order to ease the interaction among objects.
> 
> What do you think? 🚀

Hi @albamig, That's a really good proposal! 

It will ease the usability of this new class. Also, I think that in the future we can extend the `Aggregate` api and provide more `diff`-related methods mostly to analyse the previous versions of an aggregate, which I think it can be a really interesting feature in some contexts.

2021-06-11 11:49 UTC, albamig approved these changes

2021-06-11 11:50 UTC, merged